language: java

jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle
before_install:
- chmod +x gradlew

test:
  post:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
